name: Ejecutar manualmente

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v3

      - name: Mostrar mensaje
        run: echo "Este workflow se ejecutó manualmente"
